### PR TITLE
Katie

### PR DESCRIPTION
**Pull request by katielin42**
Deleted trash files we don't need, but keeping the workspace for cubeIDE

### CODE REVIEW

**Comment by ThomasOseiBonsuJr** [comment]
good stuff

**Comment by katielin42** [comment]
GO FUCK YOURSELF

**Comment by katielin42** [comment]
APPROVE MY BRANCH

**Review by ThomasOseiBonsuJr — APPROVED** [review]
even better stuff

**Comment by katielin42** [comment]
Merging.

**Pull request merged**
